2023-01-29 13:38:03,085 WARN  [main] root: Unknown error occurred!
java.lang.NullPointerException: Cannot invoke "java.util.Set.add(Object)" because "this.listeners" is null
	at client.KVStore.addListener(KVStore.java:95)
	at app_kvClient.KVClient.newConnection(KVClient.java:234)
	at app_kvClient.KVClient.handleCommand(KVClient.java:62)
	at app_kvClient.KVClient.run(KVClient.java:37)
	at app_kvClient.KVClient.main(KVClient.java:258)
2023-01-29 13:39:32,505 WARN  [main] root: Unknown error occurred!
java.lang.NullPointerException: Cannot invoke "java.util.Set.add(Object)" because "this.listeners" is null
	at client.KVStore.addListener(KVStore.java:95)
	at app_kvClient.KVClient.newConnection(KVClient.java:234)
	at app_kvClient.KVClient.handleCommand(KVClient.java:62)
	at app_kvClient.KVClient.run(KVClient.java:37)
	at app_kvClient.KVClient.main(KVClient.java:258)
2023-01-29 13:42:41,010 INFO  [main] root: try to close connection ...
2023-01-29 13:42:41,012 INFO  [main] root: tearing down the connection ...
2023-01-29 13:43:18,364 INFO  [main] root: Connection established
2023-01-29 13:43:36,358 INFO  [main] root: Send message:	 'PUT this in'
2023-01-29 13:46:35,859 INFO  [main] root: try to close connection ...
2023-01-29 13:46:35,860 INFO  [main] root: tearing down the connection ...
2023-01-29 13:46:35,863 INFO  [main] root: connection closed!
2023-01-29 13:47:26,913 INFO  [main] root: Send message:	 'PUT this in'
2023-01-29 13:47:26,918 WARN  [main] root: Unknown error occurred
java.lang.IllegalArgumentException: No enum constant shared.messages.IKVMessage.StatusType.Connection
	at java.base/java.lang.Enum.valueOf(Enum.java:274)
	at shared.messages.IKVMessage$StatusType.valueOf(IKVMessage.java:5)
	at shared.messages.KVMessage.<init>(KVMessage.java:43)
	at client.KVStore.receiveMessage(KVStore.java:175)
	at client.KVStore.put(KVStore.java:78)
	at app_kvClient.KVClient.handleCommand(KVClient.java:96)
	at app_kvClient.KVClient.run(KVClient.java:37)
	at app_kvClient.KVClient.main(KVClient.java:260)
2023-01-29 13:51:27,907 INFO  [main] root: Send message:	 'PUT ngng '
2023-01-29 13:51:27,908 WARN  [main] root: Unknown error occurred
java.lang.IllegalArgumentException: No enum constant shared.messages.IKVMessage.StatusType.
PUT
	at java.base/java.lang.Enum.valueOf(Enum.java:274)
	at shared.messages.IKVMessage$StatusType.valueOf(IKVMessage.java:5)
	at shared.messages.KVMessage.<init>(KVMessage.java:43)
	at client.KVStore.receiveMessage(KVStore.java:175)
	at client.KVStore.put(KVStore.java:78)
	at app_kvClient.KVClient.handleCommand(KVClient.java:96)
	at app_kvClient.KVClient.run(KVClient.java:37)
	at app_kvClient.KVClient.main(KVClient.java:260)
2023-01-29 13:53:13,091 INFO  [main] root: try to close connection ...
2023-01-29 13:53:13,092 INFO  [main] root: tearing down the connection ...
2023-01-29 13:53:13,095 INFO  [main] root: connection closed!
2023-01-31 12:47:05,486 INFO  [main] root: try to close connection ...
2023-01-31 12:47:05,489 INFO  [main] root: tearing down the connection ...
2023-01-31 12:47:05,489 INFO  [main] root: connection closed!
2023-01-31 12:48:29,664 INFO  [main] root: Connection established
2023-01-31 12:48:29,687 INFO  [Thread-0] root: Receive message:	 'Connection to MSRG Echo server established: /127.0.0.1 / 5001'
2023-01-31 12:48:32,435 INFO  [main] root: try to close connection ...
2023-01-31 12:48:32,435 INFO  [main] root: tearing down the connection ...
2023-01-31 12:48:32,436 INFO  [main] root: connection closed!
2023-01-31 12:53:21,160 INFO  [main] root: Connection established
2023-01-31 12:56:30,448 INFO  [main] root: Connection established
2023-01-31 12:56:43,590 INFO  [main] root: Send message:	 'PUT k v'
2023-01-31 12:56:43,613 INFO  [main] root: Receive message:	 'PUT_SUCCESS k v
'
2023-01-31 12:57:09,445 INFO  [main] root: Send message:	 'GET k null'
2023-01-31 12:57:09,447 WARN  [main] root: The following error occurred:
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
	at shared.messages.KVMessage.rmvCtrChars(KVMessage.java:100)
	at shared.messages.KVMessage.<init>(KVMessage.java:41)
	at client.KVStore.receiveMessage(KVStore.java:177)
	at client.KVStore.get(KVStore.java:88)
	at app_kvClient.KVClient.handleCommand(KVClient.java:112)
	at app_kvClient.KVClient.run(KVClient.java:37)
	at app_kvClient.KVClient.main(KVClient.java:275)
2023-01-31 13:00:07,556 INFO  [main] root: Connection established
2023-01-31 13:01:02,116 INFO  [main] root: Connection established
2023-01-31 13:01:06,059 INFO  [main] root: Send message:	 'GET k null'
2023-01-31 13:01:06,078 INFO  [main] root: Receive message:	 'GET_SUCCESS k 
'
2023-01-31 13:01:38,044 INFO  [main] root: Send message:	 'GET k null'
2023-01-31 13:01:38,046 WARN  [main] root: The following error occurred:
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
	at shared.messages.KVMessage.rmvCtrChars(KVMessage.java:100)
	at shared.messages.KVMessage.<init>(KVMessage.java:41)
	at client.KVStore.receiveMessage(KVStore.java:177)
	at client.KVStore.get(KVStore.java:88)
	at app_kvClient.KVClient.handleCommand(KVClient.java:112)
	at app_kvClient.KVClient.run(KVClient.java:37)
	at app_kvClient.KVClient.main(KVClient.java:275)
2023-01-31 13:02:35,062 INFO  [main] root: Connection established
2023-01-31 13:05:55,064 INFO  [main] root: Connection established
2023-01-31 13:06:33,033 INFO  [main] root: Connection established
2023-01-31 13:06:44,756 INFO  [main] root: Send message:	 'PUT k v'
2023-01-31 13:06:44,772 INFO  [main] root: Receive message:	 'PUT_SUCCESS k v
'
2023-01-31 13:06:49,219 INFO  [main] root: Send message:	 'GET k null'
2023-01-31 13:06:49,219 INFO  [main] root: Receive message:	 'GET_SUCCESS k 
'
2023-01-31 13:07:04,894 INFO  [main] root: Send message:	 'GET p null'
2023-01-31 13:07:04,896 WARN  [main] root: The following error occurred:
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
	at shared.messages.KVMessage.rmvCtrChars(KVMessage.java:100)
	at shared.messages.KVMessage.<init>(KVMessage.java:41)
	at client.KVStore.receiveMessage(KVStore.java:177)
	at client.KVStore.get(KVStore.java:88)
	at app_kvClient.KVClient.handleCommand(KVClient.java:112)
	at app_kvClient.KVClient.run(KVClient.java:37)
	at app_kvClient.KVClient.main(KVClient.java:275)
2023-01-31 13:08:44,539 INFO  [main] root: Send message:	 'PUT k v'
2023-01-31 13:08:44,540 WARN  [main] root: The following error occurred:
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
	at shared.messages.KVMessage.rmvCtrChars(KVMessage.java:100)
	at shared.messages.KVMessage.<init>(KVMessage.java:41)
	at client.KVStore.receiveMessage(KVStore.java:177)
	at client.KVStore.put(KVStore.java:80)
	at app_kvClient.KVClient.handleCommand(KVClient.java:96)
	at app_kvClient.KVClient.run(KVClient.java:37)
	at app_kvClient.KVClient.main(KVClient.java:275)
2023-01-31 13:09:10,229 INFO  [main] root: Connection established
2023-01-31 13:09:14,934 INFO  [main] root: try to close connection ...
2023-01-31 13:09:14,934 INFO  [main] root: tearing down the connection ...
2023-01-31 13:09:14,936 INFO  [main] root: connection closed!
2023-01-31 13:10:16,954 INFO  [main] root: Connection established
2023-01-31 13:10:34,387 INFO  [main] root: Send message:	 'PUT k c'
2023-01-31 13:12:02,811 INFO  [main] root: Connection established
2023-01-31 13:13:02,892 INFO  [main] root: Send message:	 'PUT k v'
2023-01-31 13:13:02,910 INFO  [main] root: Receive message:	 'PUT_SUCCESS k v
'
2023-01-31 13:13:10,680 INFO  [main] root: Send message:	 'PUT k v'
2023-01-31 13:13:10,683 WARN  [main] root: The following error occurred:
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
	at shared.messages.KVMessage.rmvCtrChars(KVMessage.java:100)
	at shared.messages.KVMessage.<init>(KVMessage.java:41)
	at client.KVStore.receiveMessage(KVStore.java:177)
	at client.KVStore.put(KVStore.java:80)
	at app_kvClient.KVClient.handleCommand(KVClient.java:96)
	at app_kvClient.KVClient.run(KVClient.java:37)
	at app_kvClient.KVClient.main(KVClient.java:275)
2023-01-31 13:13:34,388 INFO  [main] root: try to close connection ...
2023-01-31 13:13:34,388 INFO  [main] root: tearing down the connection ...
2023-01-31 13:13:34,390 INFO  [main] root: connection closed!
2023-01-31 13:13:45,927 INFO  [main] root: Connection established
2023-01-31 13:14:09,683 INFO  [main] root: Send message:	 'PUT k v'
2023-01-31 13:18:49,520 INFO  [main] root: Receive message:	 'PUT_SUCCESS k v
'
2023-01-31 13:19:16,727 INFO  [main] root: Connection established
2023-01-31 13:19:26,209 INFO  [main] root: Send message:	 'PUT k v'
2023-01-31 13:19:50,846 INFO  [main] root: Receive message:	 'PUT_SUCCESS k v'
2023-01-31 13:19:55,886 INFO  [main] root: Send message:	 'GET k null'
2023-01-31 13:23:15,976 WARN  [main] root: The following error occurred:
java.lang.IllegalArgumentException: No enum constant shared.messages.IKVMessage.StatusType.
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at shared.messages.IKVMessage$StatusType.valueOf(IKVMessage.java:5)
	at shared.messages.KVMessage.<init>(Unknown Source)
	at client.KVStore.receiveMessage(KVStore.java:177)
	at client.KVStore.get(KVStore.java:88)
	at app_kvClient.KVClient.handleCommand(KVClient.java:112)
	at app_kvClient.KVClient.run(KVClient.java:37)
	at app_kvClient.KVClient.main(KVClient.java:275)
2023-01-31 13:23:24,930 INFO  [main] root: Connection established
2023-01-31 13:23:27,677 INFO  [main] root: Send message:	 'GET k null'
2023-01-31 13:24:54,903 INFO  [main] root: Receive message:	 'GET_SUCCESS k null'
2023-01-31 13:25:02,802 INFO  [main] root: Send message:	 'GET p null'
2023-01-31 13:25:14,501 INFO  [main] root: Receive message:	 'GET_SUCCESS p null'
2023-01-31 13:25:25,428 INFO  [main] root: Send message:	 'GET asdfa null'
2023-01-31 13:25:25,429 INFO  [main] root: Receive message:	 'GET_SUCCESS asdfa null'
2023-01-31 13:25:32,505 INFO  [main] root: Send message:	 'PUT fasdfjk asdf'
2023-01-31 13:25:32,506 INFO  [main] root: Receive message:	 'PUT_SUCCESS fasdfjk asdf'
2023-01-31 13:27:33,459 INFO  [main] root: try to close connection ...
2023-01-31 13:27:33,459 INFO  [main] root: tearing down the connection ...
2023-01-31 13:27:33,461 INFO  [main] root: connection closed!
2023-01-31 13:28:08,794 INFO  [main] root: Connection established
2023-01-31 13:30:54,425 INFO  [main] root: try to close connection ...
2023-01-31 13:30:54,426 INFO  [main] root: tearing down the connection ...
2023-01-31 13:30:54,426 INFO  [main] root: connection closed!
2023-01-31 13:32:06,431 INFO  [main] root: Connection established
2023-01-31 13:32:10,269 INFO  [main] root: try to close connection ...
2023-01-31 13:32:10,269 INFO  [main] root: tearing down the connection ...
2023-01-31 13:32:10,270 INFO  [main] root: connection closed!
2023-01-31 13:32:23,530 INFO  [main] root: Connection established
2023-01-31 13:32:25,827 INFO  [main] root: try to close connection ...
2023-01-31 13:32:25,827 INFO  [main] root: tearing down the connection ...
2023-01-31 13:32:25,827 INFO  [main] root: connection closed!
2023-01-31 13:33:02,014 INFO  [main] root: Connection established
2023-01-31 13:33:05,614 INFO  [main] root: try to close connection ...
2023-01-31 13:33:05,614 INFO  [main] root: tearing down the connection ...
2023-01-31 13:33:05,614 INFO  [main] root: connection closed!
2023-01-31 13:38:17,428 INFO  [main] root: Connection established
2023-01-31 13:38:24,189 INFO  [main] root: try to close connection ...
2023-01-31 13:38:24,189 INFO  [main] root: tearing down the connection ...
2023-01-31 13:38:24,189 INFO  [main] root: connection closed!
2023-01-31 13:39:00,048 INFO  [main] root: Connection established
2023-01-31 13:39:21,346 INFO  [main] root: Send message:	 'PUT a '
2023-01-31 13:39:21,363 INFO  [main] root: Receive message:	 'PUT_SUCCESS a null'
2023-01-31 13:41:31,733 INFO  [main] root: Connection established
2023-01-31 13:41:43,231 INFO  [main] root: Send message:	 'PUT aa a'
2023-01-31 13:41:43,232 INFO  [main] root: Receive message:	 'PUT_SUCCESS aa a'
2023-01-31 13:41:58,409 INFO  [main] root: try to close connection ...
2023-01-31 13:41:58,409 INFO  [main] root: tearing down the connection ...
2023-01-31 13:41:58,411 INFO  [main] root: connection closed!
2023-01-31 13:44:52,406 INFO  [main] root: Connection established
2023-01-31 13:44:59,619 INFO  [main] root: try to close connection ...
2023-01-31 13:44:59,620 INFO  [main] root: tearing down the connection ...
2023-01-31 13:44:59,620 INFO  [main] root: connection closed!
2023-01-31 13:46:23,236 INFO  [main] root: Connection established
2023-01-31 13:46:26,020 INFO  [main] root: try to close connection ...
2023-01-31 13:46:26,021 INFO  [main] root: tearing down the connection ...
2023-01-31 13:46:26,021 INFO  [main] root: connection closed!
2023-01-31 13:48:06,055 INFO  [main] root: Connection established
2023-01-31 13:48:12,968 INFO  [main] root: try to close connection ...
2023-01-31 13:48:12,969 INFO  [main] root: tearing down the connection ...
2023-01-31 13:48:12,969 INFO  [main] root: connection closed!
2023-01-29 13:38:03,085 WARN  [main] root: Unknown error occurred!
java.lang.NullPointerException: Cannot invoke "java.util.Set.add(Object)" because "this.listeners" is null
	at client.KVStore.addListener(KVStore.java:95)
	at app_kvClient.KVClient.newConnection(KVClient.java:234)
	at app_kvClient.KVClient.handleCommand(KVClient.java:62)
	at app_kvClient.KVClient.run(KVClient.java:37)
	at app_kvClient.KVClient.main(KVClient.java:258)
2023-01-29 13:39:32,505 WARN  [main] root: Unknown error occurred!
java.lang.NullPointerException: Cannot invoke "java.util.Set.add(Object)" because "this.listeners" is null
	at client.KVStore.addListener(KVStore.java:95)
	at app_kvClient.KVClient.newConnection(KVClient.java:234)
	at app_kvClient.KVClient.handleCommand(KVClient.java:62)
	at app_kvClient.KVClient.run(KVClient.java:37)
	at app_kvClient.KVClient.main(KVClient.java:258)
2023-01-29 13:42:41,010 INFO  [main] root: try to close connection ...
2023-01-29 13:42:41,012 INFO  [main] root: tearing down the connection ...
2023-01-29 13:43:18,364 INFO  [main] root: Connection established
2023-01-29 13:43:36,358 INFO  [main] root: Send message:	 'PUT this in'
2023-01-29 13:46:35,859 INFO  [main] root: try to close connection ...
2023-01-29 13:46:35,860 INFO  [main] root: tearing down the connection ...
2023-01-29 13:46:35,863 INFO  [main] root: connection closed!
2023-01-29 13:47:26,913 INFO  [main] root: Send message:	 'PUT this in'
2023-01-29 13:47:26,918 WARN  [main] root: Unknown error occurred
java.lang.IllegalArgumentException: No enum constant shared.messages.IKVMessage.StatusType.Connection
	at java.base/java.lang.Enum.valueOf(Enum.java:274)
	at shared.messages.IKVMessage$StatusType.valueOf(IKVMessage.java:5)
	at shared.messages.KVMessage.<init>(KVMessage.java:43)
	at client.KVStore.receiveMessage(KVStore.java:175)
	at client.KVStore.put(KVStore.java:78)
	at app_kvClient.KVClient.handleCommand(KVClient.java:96)
	at app_kvClient.KVClient.run(KVClient.java:37)
	at app_kvClient.KVClient.main(KVClient.java:260)
2023-01-29 13:51:27,907 INFO  [main] root: Send message:	 'PUT ngng '
2023-01-29 13:51:27,908 WARN  [main] root: Unknown error occurred
java.lang.IllegalArgumentException: No enum constant shared.messages.IKVMessage.StatusType.
PUT
	at java.base/java.lang.Enum.valueOf(Enum.java:274)
	at shared.messages.IKVMessage$StatusType.valueOf(IKVMessage.java:5)
	at shared.messages.KVMessage.<init>(KVMessage.java:43)
	at client.KVStore.receiveMessage(KVStore.java:175)
	at client.KVStore.put(KVStore.java:78)
	at app_kvClient.KVClient.handleCommand(KVClient.java:96)
	at app_kvClient.KVClient.run(KVClient.java:37)
	at app_kvClient.KVClient.main(KVClient.java:260)
2023-01-29 13:53:13,091 INFO  [main] root: try to close connection ...
2023-01-29 13:53:13,092 INFO  [main] root: tearing down the connection ...
2023-01-29 13:53:13,095 INFO  [main] root: connection closed!
2023-01-31 13:05:34,895 INFO  [main] root: Connection established
2023-01-31 13:05:40,373 INFO  [main] root: Send message:	 'PUT foo bar'
2023-01-31 13:05:40,383 INFO  [main] root: Receive message:	 'PUT_SUCCESS foo bar
'
2023-01-31 13:18:19,070 INFO  [main] root: Connection established
2023-01-31 13:18:45,344 INFO  [main] root: Send message:	 'PUT foo bar'
2023-01-31 13:18:45,361 INFO  [main] root: Receive message:	 'PUT_SUCCESS foo bar
'
2023-01-31 13:20:30,737 INFO  [main] root: Connection established
2023-01-31 13:20:36,511 INFO  [main] root: Send message:	 'PUT foo bar'
2023-01-31 13:24:55,723 INFO  [main] root: Receive message:	 'PUT_SUCCESS foo bar
'
2023-01-31 13:25:24,309 INFO  [main] root: try to close connection ...
2023-01-31 13:25:24,310 INFO  [main] root: tearing down the connection ...
2023-01-31 13:25:24,312 INFO  [main] root: connection closed!
2023-01-31 13:26:03,408 INFO  [main] root: try to close connection ...
2023-01-31 13:26:03,409 INFO  [main] root: tearing down the connection ...
2023-01-31 13:26:03,412 INFO  [main] root: connection closed!
2023-01-31 13:26:18,443 INFO  [main] root: Connection established
2023-01-31 13:26:22,371 INFO  [main] root: Send message:	 'PUT foo bar'
2023-01-31 13:26:22,380 INFO  [main] root: Receive message:	 'PUT_SUCCESS foo bar
'
2023-01-31 13:26:56,845 INFO  [main] root: try to close connection ...
2023-01-31 13:26:56,845 INFO  [main] root: tearing down the connection ...
2023-01-31 13:26:56,848 INFO  [main] root: connection closed!
2023-01-31 13:27:39,618 INFO  [main] root: Connection established
2023-01-31 13:27:56,172 INFO  [main] root: Send message:	 'PUT foo bar'
2023-01-31 13:28:12,332 INFO  [main] root: Receive message:	 'PUT_SUCCESS foo bar
'
2023-01-31 13:29:53,947 INFO  [main] root: Connection established
2023-01-31 13:29:57,409 INFO  [main] root: Send message:	 'PUT foo bar'
2023-01-31 13:30:16,641 INFO  [main] root: Receive message:	 'PUT_SUCCESS foo bar
'
2023-01-31 13:30:55,939 INFO  [main] root: try to close connection ...
2023-01-31 13:30:55,940 INFO  [main] root: tearing down the connection ...
2023-01-31 13:30:55,943 INFO  [main] root: connection closed!
2023-01-31 13:31:02,422 INFO  [main] root: Connection established
2023-01-31 13:31:21,023 INFO  [main] root: Send message:	 'PUT foo bruh'
2023-01-31 13:32:10,764 INFO  [main] root: Receive message:	 'PUT_SUCCESS foo bruh
'
2023-01-31 13:32:19,202 INFO  [main] root: Send message:	 'GET foo null'
2023-01-31 13:32:19,205 WARN  [main] root: The following error occurred:
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
	at shared.messages.KVMessage.rmvCtrChars(KVMessage.java:100)
	at shared.messages.KVMessage.<init>(KVMessage.java:41)
	at client.KVStore.receiveMessage(KVStore.java:175)
	at client.KVStore.get(KVStore.java:86)
	at app_kvClient.KVClient.handleCommand(KVClient.java:112)
	at app_kvClient.KVClient.run(KVClient.java:37)
	at app_kvClient.KVClient.main(KVClient.java:275)
2023-01-31 13:42:57,110 INFO  [main] root: Connection established
2023-01-31 13:43:01,139 INFO  [main] root: Send message:	 'PUT foo bar'
2023-01-31 13:43:01,147 INFO  [main] root: Receive message:	 'PUT_SUCCESS foo bar
'
2023-01-31 13:43:19,920 INFO  [main] root: Send message:	 'PUT hello friend'
2023-01-31 13:43:19,929 WARN  [main] root: The following error occurred:
java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 0
	at shared.messages.KVMessage.rmvCtrChars(KVMessage.java:100)
	at shared.messages.KVMessage.<init>(KVMessage.java:41)
	at client.KVStore.receiveMessage(KVStore.java:175)
	at client.KVStore.put(KVStore.java:78)
	at app_kvClient.KVClient.handleCommand(KVClient.java:96)
	at app_kvClient.KVClient.run(KVClient.java:37)
	at app_kvClient.KVClient.main(KVClient.java:275)
